name: product_catalog
description: "A Flutter e-commerce Product Catalog app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI and Icons
  cupertino_icons: ^1.0.8
  
  # State Management
  provider: ^6.1.5
  
  # HTTP Requests
  http: ^1.5.0
  
  # Image handling
  cached_network_image: ^3.4.1
  
  # Navigation
  go_router: ^16.2.4
  
  # UI Components
  flutter_staggered_grid_view: ^0.7.0
  
  # Utilities
  intl: ^0.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Assets for sample product images
  assets:
    - assets/images/
